services:
  agents:
    build:
      context: .
    restart: "no"
    volumes:
      - ~/.config/gcloud:/home/app/.config/gcloud:ro
      - ./audio:/app/audio
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              count: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MODEL_RUNNER_URL
      - MODEL_RUNNER_MODEL
