services:
  agents:
    build:
        context: .
    restart: no
    models:
      qwen3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

models:
  qwen3:
    model: ai/qwen3
    context_size: 8192
    runtime_flags:
      - --no-prefill-assistant
